name: brill_prime
description: Brill Prime Project

environment:
  sdk: '^3.5.0'
  flutter: ">=3.24.0"

dependencies:
  cached_network_image: ^3.2.3
  change_app_package_name: ^1.5.0
  crypto: ^3.0.3
  cupertino_icons: ^1.0.8
  device_info_plus: ^10.1.2
  dots_indicator: ^4.0.1
  file_picker: ^10.2.0
  firebase_auth: ^5.3.1
  firebase_core: ^3.12.1
  flutter:
    sdk: flutter
  flutter_card_io: ^2.0.0
  flutter_facebook_auth: ^7.1.1
  flutter_inappwebview: ^6.1.3
  flutter_screenutil: ^5.5.3+2
  flutter_svg: ^2.2.0
  fluttertoast: ^8.2.1
  geocoding: ^4.0.0
  geolocator: ^13.0.1
  go_router: ^16.0.0
  google_maps_flutter: ^2.10.0
  google_sign_in: ^6.2.1
  hive_flutter: ^1.1.0
  http: ^1.4.0
  http_parser: ^4.0.2
  iconsax: ^0.0.8
  image_picker: ^1.1.2
  intl: ^0.20.2
  jiffy: ^6.2.1
  local_auth: ^2.1.7
  local_auth_android: ^1.0.34
  mobile_scanner: ^7.0.1
  package_info_plus: ^8.0.2
  permission_handler: ^12.0.1
  pin_code_fields: ^8.0.1
  provider: ^6.0.2
  qr_flutter: ^4.1.0
  share_plus: ^7.2.2
  shared_preferences: ^2.0.13
  sign_in_with_apple: ^6.1.2
  simple_gradient_text: ^1.3.0
  supabase_flutter: ^2.8.4
  url_launcher: ^6.1.10
  web_socket_channel: null
dev_dependencies:
  build_runner: ^2.4.13
  flutter_launcher_icons: ^0.14.4
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1
  integration_test:
    sdk: flutter
  mockito: ^5.4.4
